Dockerfile.rpm, pacifica-upload-status.spec
This updates the docker rpm build process to reflect new changes
made in the deployment of the status tool
=> fix #17 updates docker rpm build

application/config/routes.php, application/controllers/Cart_api.php, application/models/Status_api_model.php, application/resources/scripts/status_common.js, application/views/upload_item_view.html
=> Issue 124 single transaction status fixes

application/models/System_setup_model.php
This should make the db writes to sqlite work properly
=> Fixes #102

application/controllers/Ajax_api.php, application/controllers/Baseline_api_controller.php, application/resources/scripts/overview.js
This should fix the cases where a user is staff, but is not assigned to any proposals
=> Fixes #104

application/models/Status_api_model.php
This catches the folder structure formatting call and injects the proper sorting info before display
Fixes #109
=> Fix file sorting display issues

application/models/Cart_api_model.php, application/models/System_setup_model.php
=> Added ‘hashtype’ and ‘hashsum’ to the ’cart_items’ table generation specs

application/helpers/user_helper.php
=> Normalizes usernames to be all lower-case

application/config/pacifica.php, application/controllers/Status_api.php, application/resources/scripts/emsl_mgmt_view.js, application/views/emsl_template/top.php, application/views/emsl_template/view_footer_short.php, application/views/emsl_template/view_header.php, application/views/pnnl_template/view_header.php
This starts the process of pulling hard-coded MyEMSL references out of the status page interface.
Addresses #38
=> Remove visible MyEMSL references

application/helpers/myemsl_api_helper.php, application/views/upload_item_view.html
This adds in support for showing the actual name associated with the transaction key/value for "User of Record". This is kind of a hack for now until we have a chance to refactor the transactions table properly
=> Issue 122 user of record name fix

application/resources/scripts/overview.js
=> Cleaning up overview.js syntax

application/resources/scripts/emsl_mgmt_view.js, application/resources/scripts/myemsl_file_download.js
ESLint turned up a bunch of inconsistencies in my JS code. Fixing them.
=> Additional syntax and format fixup/cleanup for javascript

application/config/config.php, application/models/Data_transfer_api_model.php, application/resources/scripts/doi_data_transfer.js, application/resources/stylesheets/doi_transfer_cart.css, application/views/doi_transfer_cart_table_view.html, application/views/upload_item_view.html
This adds better display of data set information from DRHub, as well as providing the notification API that DRHub can use to communicate data set DOI minting status.
=> Issue 212a additional drhub integration fixes

application/models/System_setup_model.php
Fixes #226 
This should fix the issue with the database create scripts trying to run every single time the app is called
=> Issue 226 fix db create process

application/models/System_setup_model.php, application/resources/scripts/doi_minting.js
This should clear up the following...
* Bad database object crash when checking for table existence during setup due to a misconfigured database component
* Added the xhrfield "withCredentials: true" to the doi minting call in doi_minting.js to make sure that CORS works properly with the minting service.
=> Minor cleanup

application/config/data_release.php, application/controllers/Status_api.php, application/resources/scripts/doi_minting.js
Configuration is located in the data_release.php config file
=> Making the originating research organization a configurable option

application/resources/scripts/doi_minting.js
=> Changing dynamic DOI URL for submission

application/config/config.php, application/controllers/Status_api.php, application/models/Doi_minting_model.php, application/resources/scripts/doi_minting.js, application/resources/scripts/doi_notation.js, application/resources/scripts/overview.js, application/resources/stylesheets/combined.css, application/views/upload_item_view.html
Changes to better display DOI data
=> Issue 252 doi status revision

application/resources/scripts/doi_notation.js
to remove multiple instances of DOI Reference in item block
=> Tweaking JS object building logic

application/resources/scripts/doi_notation.js
=> Straightens out DOI reference link formatting

application/resources/scripts/doi_minting.js, application/resources/stylesheets/combined.css
=> Clearing up rendering issues with DOI Link Copying button

application/models/Status_api_model.php, application/resources/scripts/myemsl_file_download.js, application/views/upload_item_view.html
=> Server side cleanup for no files glitch

application/resources/scripts/doi_notation.js, application/views/upload_item_view.html
Looks like this clears up the multiple entry issue
=> Issue 292 multiplying doi refs

application/config/pacifica.php, application/resources/scripts/doi_notation.js
This updates the application bundle version to 2.3.0 (I just picked a semi-arbitrary starting point) and returns the auto-update interval to the doi reference display code
=> Issue 292 doi reference display issues

README.md, application/config/ingester_status.php, application/config/pacifica.php, application/controllers/Ajax_api.php, application/controllers/Baseline_api_controller.php, application/controllers/Status_api.php, application/controllers/Test_api.php, application/helpers/myemsl_api_helper.php, application/helpers/user_helper.php, application/models/Data_transfer_api_model.php, application/models/Myemsl_api_model.php, application/models/Status_api_model.php, application/resources/scripts/data_release.js, application/resources/scripts/doi_minting.js, application/resources/scripts/emsl_mgmt_view.js, application/resources/scripts/overview.js, application/resources/scripts/status_common.js, application/resources/stylesheets/selector.css, application/views/doi_transfer_cart_table_view.html, application/views/project_selector_insert.html, application/views/proposal_selector_insert.html, application/views/selector_module_insert.html, application/views/upload_item_view.html
Initial switchover appears functional
=> Initial changes to switch from proposal to project nomenclature

application/config/pacifica.php, application/controllers/Ajax_api.php, application/controllers/Status_api.php, application/models/Doi_minting_model.php, application/resources/scripts/data_release.js, application/resources/scripts/doi_minting.js, application/resources/scripts/overview.js, application/resources/stylesheets/combined.css, application/views/page_chrome/view_header.php, application/views/selector_module_insert.html, application/views/upload_item_view.html
This should be a mostly final version of the upload status page with both paging and data releaser restrictions in place
=> Issue 300 restrict data releasers

application/config/pacifica.php, application/controllers/Cart_api.php, application/controllers/Status_api.php, application/helpers/item_helper.php, application/resources/scripts/myemsl_file_download.js, application/resources/scripts/single_item_view.js, application/views/cart_create_dialog_view.html, application/views/upload_item_view.html
to handle things like enabling single file downloads and whether to require auth to download carts
=> Adding in configuration switches

application/controllers/Cart_api.php, application/controllers/Status_api.php, application/models/Cart_api_model.php, application/resources/scripts/data_release.js, application/resources/scripts/doi_minting.js, application/resources/scripts/myemsl_file_download.js, application/resources/stylesheets/combined.css, application/views/upload_item_view.html
This should get all the changes and fixes that I made in the backported branch and bring them home to roost in master
=> Forward-porting backported changes

application/controllers/Status_api.php
Adding in some simple logic to the data visibility checking code to make sure we even have transaction data to use for evaluation
=> Fix #318 - Adding logic to visibility eval code

application/config/pacifica.php
Upping version number in config file to 2.7.1 to match tag
=> Pushing up a corrected version number

application/controllers/Ajax_api.php, application/helpers/myemsl_api_helper.php
Replaced a hard-coded relationship UUID with the proper looked up ver sion from the relationships table
=> Remove hard-coded UUID

application/resources/scripts/doi_notation.js, application/resources/stylesheets/combined.css, application/views/upload_item_view.html
Changing these to more clearly indicate what they actually mean
=> Updating the verbiage on the dataset release status ribbons
